#!/usr/bin/env python3
"""Generate docs/cli-reference.md from erm's argparse parsers.

Run via `make docs-cli`. The output is committed so the lightweight docs build
(`mkdocs build --no-project`) can serve it without importing erm's runtime
stack. CI re-runs this and fails on any diff, so the page can never drift from
the actual `--help`.
"""

from __future__ import annotations

from pathlib import Path

from erm.cli import _build_remove_parser, _build_validate_parser

BANNER = (
    "<!-- DO NOT EDIT. Generated by scripts/gen_cli_docs.py from erm's argparse\n"
    "     parsers. Run `make docs-cli` to regenerate after changing the CLI. -->"
)

INTRO = """# CLI reference

Every flag `erm` accepts, generated directly from the command-line parser so it
always matches the installed version. For prose on *which* knobs to reach for,
see the [tuning & workflow guide](usage.md) and [recipes](recipes.md); for
setup, see [installation](installation.md).
"""


def _section(title: str, parser) -> str:
    return f"## `{title}`\n\n```text\n{parser.format_help().rstrip()}\n```\n"


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / "docs" / "cli-reference.md"

    body = "\n".join(
        [
            BANNER,
            "",
            INTRO,
            _section("erm", _build_remove_parser()),
            _section("erm validate", _build_validate_parser()),
        ]
    )
    out_path.write_text(body.rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {out_path.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
